version: '2'

services:

  webshark:
    image: harbor.donghwa.dev:4443/seo/webshark
    container_name: webshark
    expose:
      - "8085"
    ports:
      - "8085:8085"
    volumes:
      - ./data/pcap:/data/pcap
